name: Build and Deploy Vue App

on:
  push:
    branches:
      - main # Запускаем только при пушах в основную ветку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Используем виртуальную машину Ubuntu последней версии
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Загружаем код из текущего коммита

      - name: Cache Node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm # Путь к каталогу с кешированными модулями
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Версия NodeJS

      - name: Install pnpm
        run: npm install --global corepack@latest # Устанавливаем pnpm

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: pnpm install # Устанавливаем зависимости
      
      - name: Build application
        run: export BASE_PATH="/" && export PORT=3000 && pnpm run build # Выполняем команду сборки приложения
      
      - name: Deploy to server via SFTP (/tmp)
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.PROD_HOST }} # IP-адрес сервера
          USERNAME: ${{ secrets.PROD_USERNAME }} # Имя пользователя
          PASSWORD: ${{ secrets.PROD_PASSWORD }} # Пароль доступа к серверу 
          PORT: 22 # Порт подключения
        with:
          source: "./artifacts/resume-site/dist/public/" # Папка со скомпилированным приложением
          target: "/tmp" # Куда выкладывать результат на сервере
