name: Build and Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm install --global corepack@latest

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: pnpm install
      
      - name: Build application
        run: export BASE_PATH="/" && export PORT=3000 && pnpm run build
      
      - name: Deploy to server via SFTP (/tmp)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 22
          # source: "./artifacts/resume-site/dist/public/"
          # target: "/tmp"
          script: |
            cd /tmp
            rm -rf vue-app-build
            mkdir vue-app-build && cd vue-app-build
            tar xzf <(curl --silent ${{ github.server_url }}/${{ github.repository }}/actions/artifacts/${{ github.run_id }}.tar.gz) # Скачиваем архив с результатом сборки из Artifacts
            rsync -avz --delete ./dist/ /var/www/myapp/public_html
            sudo chown -R www-data:www-data /var/www/myapp/public_html
